name: pumpkin_bites_new
description: "Daily bite-sized wisdom for personal growth"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.7.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.6
  firebase_storage: ^12.4.5
  
  # UI
  cupertino_icons: ^1.0.8
  provider: ^6.1.4
  cached_network_image: ^3.4.1
  flutter_staggered_grid_view: ^0.7.0
  
  # Audio
  just_audio: ^0.10.0
  just_audio_background: ^0.0.1-beta.16
  audio_session: ^0.2.1
  rxdart: ^0.28.0
  
  # Utils
  intl: ^0.20.2
  path_provider: ^2.1.5
  shared_preferences: ^2.2.2
  url_launcher: ^6.3.1
  uuid: ^4.5.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true