name: pumpkin_bites_new
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase
  firebase_core: 3.13.0
  firebase_auth: 5.5.2
  cloud_firestore: 5.6.6
  firebase_storage: 12.4.5
  
  # UI
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  cached_network_image: ^3.2.3
  flutter_staggered_grid_view: ^0.6.2
  
  # Audio
  just_audio: ^0.9.34
  just_audio_background: ^0.0.1-beta.10
  audio_session: ^0.1.16
  rxdart: ^0.27.7
  
  # Sharing
  share_plus: ^7.2.1
  
  # Utils
  intl: ^0.18.1
  path_provider: ^2.0.15
  shared_preferences: ^2.1.1
  url_launcher: ^6.1.11
  uuid: ^3.0.7
  
  # Image Generation
  screenshot: ^3.0.0
  image_picker: ^1.0.4
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true